name: likeetube
description: A new Flutter application.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  responsive_widgets: ^2.0.1
  flushbar: ^1.10.4
  provider: ^4.3.2+2
  http: ^0.12.2
  permission_handler: 5.0.1+1
  ext_storage: ^1.0.3
  video_player: ^0.10.12+2
  sembast: ^2.4.7+6
  share_extend: "^1.1.9"
  package_info: ^0.4.3
  firebase_admob: ^0.9.3+4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.3
  flutter_native_splash: ^0.1.9
  change_app_package_name: ^0.1.2
  flutter_launcher_name: ^0.0.1
  flutter_automation: ^1.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/cover.jpg
    - assets/images/icon/icon.png
    - assets/images/splash/splash.png
  fonts:
    - family: Gilory
      fonts:
        - asset: assets/fonts/Gilroy.otf
    - family: GiloryL
      fonts:
        - asset: assets/fonts/GilroyL.otf
# for changing app icon
flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/icon/icon.png"
# for changing splash screen
flutter_native_splash:
  image: assets/images/splash/splash.png
  color: "0F111A"
  android_disable_fullscreen: true
  ios: false

# for changing app Title in Launcher
flutter_launcher_name:
  name: "likeetube"